### ISSUE TITLE
1.6.0 ignores cli arguments

### ISSUE THREAD

**Issue by Bouke** [less/less-plugin-clean-css#44]
When command line arguments are provided, they no longer have any impact on the outcome.

# Given `file.less`:
```less
/*! hello */
/*! world */
foo { bar: 1 }
```

and compiled using:
```bash
lessc file.less --clean-css="--s1 --advanced --compatibility=ie8" file.css
```

# Expected outcome:
```css
/*! hello */foo{bar:1}
```

# Actual outcome:
```css
/*! hello *//*! hello */foo{bar:1}
```

# Context
`package.json`:
```json
{
  "dependencies": {
    "less": "^4.2.0",
    "less-plugin-clean-css": "^1.6.0"
  }
}
```
```
clean-css: 5.3.3
less-plugin-clean-css: 1.6.0
less: 4.2.0
```
